//! Build-time code generator for the `psl2` crate.
//!
//! Reads the vendored `list/public_suffix_list.dat`, normalizes every rule to
//! ASCII/punycode (so the runtime never has to), and writes the compact
//! `src/list.txt` data file that the library embeds via `include_str!`.
//!
//! This runs at *publish* time (in CI), not on every consumer build — that is
//! what keeps downstream builds fast. Run it locally with:
//!
//! ```text
//! cargo run -p xtask
//! ```

use std::fs;
use std::process::ExitCode;

const SRC: &str = "list/public_suffix_list.dat";
const DST: &str = "src/list.txt";

fn main() -> ExitCode {
    let raw = match fs::read_to_string(SRC) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: cannot read {SRC}: {e}");
            return ExitCode::FAILURE;
        }
    };

    let version = raw
        .lines()
        .find_map(|l| l.trim().strip_prefix("// VERSION:"))
        .map(str::trim)
        .unwrap_or("unknown");

    let mut out = String::with_capacity(raw.len());
    out.push_str("# AUTO-GENERATED by `cargo run -p xtask`. DO NOT EDIT BY HAND.\n");
    out.push_str("# Source: https://publicsuffix.org/list/public_suffix_list.dat\n");
    out.push_str("# The suffix data below is (c) Mozilla Foundation, licensed MPL-2.0.\n");
    out.push_str(&format!("# PSL VERSION: {version}\n"));
    out.push_str("# Line format: <section:I|P><kind:N|W|E><space><ascii-rule>\n");

    // The list is split into an ICANN section and a PRIVATE section. Everything
    // before the PRIVATE marker is treated as ICANN.
    let mut section = b'I';
    let mut count = 0usize;
    let mut skipped = 0usize;

    for line in raw.lines() {
        let t = line.trim();
        if t.is_empty() {
            continue;
        }
        if let Some(comment) = t.strip_prefix("//") {
            if comment.contains("BEGIN PRIVATE DOMAINS") {
                section = b'P';
            } else if comment.contains("BEGIN ICANN DOMAINS") {
                section = b'I';
            }
            continue;
        }

        // A rule occupies the whole line; defensively take the first token.
        let rule = t.split_whitespace().next().unwrap_or("");
        if rule.is_empty() {
            continue;
        }

        let (kind, domain_part) = if let Some(r) = rule.strip_prefix('!') {
            (b'E', r) // exception: store the full rule sans '!'
        } else if let Some(r) = rule.strip_prefix("*.") {
            (b'W', r) // wildcard "*.Y": store just Y
        } else if rule == "*" {
            (b'W', "") // a bare wildcard (none today), Y is empty
        } else {
            (b'N', rule) // ordinary rule
        };

        let ascii = match idna::domain_to_ascii(domain_part) {
            Ok(a) => a,
            Err(e) => {
                eprintln!("warning: skipping rule {rule:?}: idna error: {e:?}");
                skipped += 1;
                continue;
            }
        };

        out.push(section as char);
        out.push(kind as char);
        out.push(' ');
        out.push_str(&ascii);
        out.push('\n');
        count += 1;
    }

    if let Err(e) = fs::write(DST, &out) {
        eprintln!("error: cannot write {DST}: {e}");
        return ExitCode::FAILURE;
    }

    eprintln!("wrote {DST}: {count} rules (PSL {version}); {skipped} skipped");
    ExitCode::SUCCESS
}
