//! Build-time code generator for the `psl2` crate.
//!
//! Reads the vendored `list/public_suffix_list.dat`, normalizes every rule to
//! ASCII/punycode (so the runtime never has to), and writes the data the
//! library embeds and queries with a no-alloc, index-driven binary search:
//!
//! * `src/{rules,wildcards,exceptions}.txt` — sorted `rule\tS` lines
//!   (`S` = section: `I` ICANN, `P` PRIVATE), joined by `\n`, no trailing `\n`.
//! * `src/{rules,wildcards,exceptions}.idx` — for each line, its `u32` LE byte
//!   offset into the matching `.txt`, so the runtime can index lines directly
//!   instead of scanning for newlines.
//! * `src/psl_version.txt` — the upstream list version string.
//! * `src/generated.rs` — `MAX_RULE_LABELS`, used to bound lookups.
//!
//! Wildcard rules `*.Y` are stored as `Y` (e.g. `ck` for `*.ck`); exception
//! rules `!X` as `X` (e.g. `www.ck`).
//!
//! Runs at *publish* time (in CI), not on every consumer build:
//!
//! ```text
//! cargo run -p xtask
//! ```

use std::collections::BTreeMap;
use std::fs;
use std::process::ExitCode;

const SRC: &str = "list/public_suffix_list.dat";

fn main() -> ExitCode {
    let raw = match fs::read_to_string(SRC) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: cannot read {SRC}: {e}");
            return ExitCode::FAILURE;
        }
    };

    let version = raw
        .lines()
        .find_map(|l| l.trim().strip_prefix("// VERSION:"))
        .map(str::trim)
        .unwrap_or("unknown")
        .to_string();

    // BTreeMap keeps each section sorted by rule and de-duplicates.
    let mut rules: BTreeMap<String, char> = BTreeMap::new();
    let mut wildcards: BTreeMap<String, char> = BTreeMap::new();
    let mut exceptions: BTreeMap<String, char> = BTreeMap::new();

    let mut section = 'I';
    let mut skipped = 0usize;

    for line in raw.lines() {
        let t = line.trim();
        if t.is_empty() {
            continue;
        }
        if let Some(comment) = t.strip_prefix("//") {
            if comment.contains("BEGIN PRIVATE DOMAINS") {
                section = 'P';
            } else if comment.contains("BEGIN ICANN DOMAINS") {
                section = 'I';
            }
            continue;
        }

        let rule = t.split_whitespace().next().unwrap_or("");
        if rule.is_empty() {
            continue;
        }

        let (table, domain_part): (&mut BTreeMap<String, char>, &str) =
            if let Some(r) = rule.strip_prefix('!') {
                (&mut exceptions, r)
            } else if let Some(r) = rule.strip_prefix("*.") {
                (&mut wildcards, r)
            } else if rule == "*" {
                (&mut wildcards, "")
            } else {
                (&mut rules, rule)
            };

        let ascii = match idna::domain_to_ascii(domain_part) {
            Ok(a) => a,
            Err(e) => {
                eprintln!("warning: skipping rule {rule:?}: idna error: {e:?}");
                skipped += 1;
                continue;
            }
        };
        if ascii.contains('\t') || ascii.contains('\n') {
            eprintln!("warning: skipping rule {rule:?}: illegal character");
            skipped += 1;
            continue;
        }

        table.insert(ascii, section);
    }

    // `MAX_RULE_LABELS` bounds how many trailing labels a lookup must consider:
    // rules count their labels; a `*.Y` wildcard counts `Y`'s labels plus one.
    let labels = |s: &str| s.split('.').count();
    let max_rule_labels = rules
        .keys()
        .map(|r| labels(r))
        .chain(exceptions.keys().map(|r| labels(r)))
        .chain(wildcards.keys().map(|y| labels(y) + 1))
        .max()
        .unwrap_or(1);

    if let Err(code) = write_block("src/rules", &rules)
        .and_then(|_| write_block("src/wildcards", &wildcards))
        .and_then(|_| write_block("src/exceptions", &exceptions))
        .and_then(|_| write_file("src/psl_version.txt", version.as_bytes()))
        .and_then(|_| {
            let gen = format!(
                "// AUTO-GENERATED by `cargo run -p xtask`. DO NOT EDIT.\n\
                 /// Maximum number of labels in any rule; bounds lookups.\n\
                 pub(crate) const MAX_RULE_LABELS: usize = {max_rule_labels};\n"
            );
            write_file("src/generated.rs", gen.as_bytes())
        })
    {
        return code;
    }

    eprintln!(
        "wrote {} rules, {} wildcards, {} exceptions (PSL {version}); \
         MAX_RULE_LABELS={max_rule_labels}; {skipped} skipped",
        rules.len(),
        wildcards.len(),
        exceptions.len(),
    );
    ExitCode::SUCCESS
}

/// Write one sorted block as `<stem>.txt` (`rule\tS` lines) plus `<stem>.idx`
/// (a `u32` LE line-start offset per line).
fn write_block(stem: &str, entries: &BTreeMap<String, char>) -> Result<(), ExitCode> {
    let mut text = String::new();
    let mut idx = Vec::with_capacity(entries.len() * 4);
    for (rule, section) in entries {
        if !text.is_empty() {
            text.push('\n');
        }
        let off = u32::try_from(text.len()).expect("block exceeds 4 GiB");
        idx.extend_from_slice(&off.to_le_bytes());
        text.push_str(rule);
        text.push('\t');
        text.push(*section);
    }
    write_file(&format!("{stem}.txt"), text.as_bytes())?;
    write_file(&format!("{stem}.idx"), &idx)
}

fn write_file(path: &str, bytes: &[u8]) -> Result<(), ExitCode> {
    fs::write(path, bytes).map_err(|e| {
        eprintln!("error: cannot write {path}: {e}");
        ExitCode::FAILURE
    })
}
